# Generated by Django 3.1.5 on 2021-01-21 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assessmentCriterias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['criteria'],
            },
        ),
        migrations.CreateModel(
            name='markingGrids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='descriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descp', models.CharField(max_length=100)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Feedback_Management_System.assessmentcriterias')),
            ],
            options={
                'ordering': ['descp'],
            },
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Feedback_Management_System.descriptions')),
            ],
            options={
                'ordering': ['comment'],
            },
        ),
        migrations.AddField(
            model_name='assessmentcriterias',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Feedback_Management_System.markinggrids'),
        ),
    ]
