# Generated by Django 3.1.5 on 2021-01-26 15:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback_Management_System', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptions',
            name='descp',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
