# Generated by Django 3.1.6 on 2021-02-06 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback_Management_System', '0002_auto_20210126_2137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comments',
        ),
    ]
