# Generated by Django 3.1.6 on 2021-03-01 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback_Management_System', '0005_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='criteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crt', to='Feedback_Management_System.assessmentcriterias'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='grid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Grid', to='Feedback_Management_System.markinggrids'),
        ),
    ]
