# Generated by Django 3.1.6 on 2021-03-01 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback_Management_System', '0006_auto_20210301_1930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marks',
            options={},
        ),
    ]
