# Generated by Django 3.1.6 on 2021-03-08 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback_Management_System', '0008_auto_20210301_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descriptions',
            options={'ordering': ['criteria']},
        ),
    ]
