# Generated by Django 3.1.6 on 2021-03-19 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback_Management_System', '0010_auto_20210314_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptions',
            name='grid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='griding', to='Feedback_Management_System.markinggrids'),
        ),
        migrations.AlterField(
            model_name='descriptions',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Criteria', to='Feedback_Management_System.assessmentcriterias'),
        ),
    ]
