# Generated by Django 3.1.6 on 2021-03-19 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback_Management_System', '0013_auto_20210319_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descriptions',
            name='grid',
        ),
        migrations.AlterField(
            model_name='descriptions',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Feedback_Management_System.assessmentcriterias'),
        ),
    ]
