# Generated by Django 3.1.6 on 2021-04-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Management_System', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='wlvid',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
