# Generated by Django 3.1.6 on 2021-04-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Management_System', '0003_auto_20210408_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='wlvid',
            field=models.IntegerField(blank=True, max_length=8, null=True),
        ),
    ]
