# Generated by Django 3.1.6 on 2021-04-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Management_System', '0004_auto_20210408_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='wlvid',
            field=models.CharField(blank=True, default=1, max_length=8),
            preserve_default=False,
        ),
    ]
